version: '3'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn api.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
#    command: npm run start
#    ports:
#      - "3000:3000"
    volumes:
      - build_folder:/frontend/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder: